//DEBUG=true;
Calibrar=require("./stages/calibracion.js");
Tienda=require("./stages/tienda.js");
calibracion=new Calibrar();
//memorama=new Memorama();
//basketball=new Basketball();
tienda=new Tienda();
//ColorStage=require("../src/trackingcolor.js");
//var tracking=new ColorStage();
ARWeb=require("../src/class/arweb.js");
arweb=new ARWeb({"width":1000,"height":800,"elemento":"ra"});
arweb.init();
//arweb.addStage(tracking);
arweb.addStage(calibracion);
arweb.addStage(tienda);
//arweb.addStage(memorama);
//arweb.addStage(basketball);
arweb.run();